# Generated by Django 4.2 on 2023-04-30 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qmss', '0002_staffextra_delete_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='pdf_files/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recepients', models.ManyToManyField(related_name='pdf_files_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_files_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
