# Generated by Django 4.2 on 2023-04-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmss', '0003_pdffile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdffile',
            old_name='recepients',
            new_name='recipients',
        ),
    ]
