# Generated by Django 4.2 on 2023-05-01 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qmss', '0004_rename_recepients_pdffile_recipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='recipients',
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='qmss.pdffile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_objects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
