# Generated by Django 4.2 on 2023-05-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmss', '0007_permission_pdf_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission_pdf',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
