# Generated by Django 4.2 on 2023-05-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmss', '0008_alter_permission_pdf_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='pdf_file',
            field=models.FileField(upload_to='media/pdf_files/%Y/%m/%d'),
        ),
    ]
