# Generated by Django 4.2 on 2023-05-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmss', '0009_alter_pdffile_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='pdf_file',
            field=models.FileField(upload_to='pdf_files/%Y/%m/%d'),
        ),
    ]
